# Site settings
title: Vigor CMS
email: admins@liveinvigor.com
description: >
  Vigor CMS with wellness content
  and blog posts.

baseurl: "" # the subpath of your site, e.g. /blog/
url: http://cms.livinvigor.com # the base hostname & protocol for your site
# git_address: https://github.com/aksakalli/jekyll-doc-theme
# git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: yeti

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/Phoenix
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
